###服务启动端口号
server:
  port: 9001
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: farm-expert
      ###上传文件大小设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://114.67.79.57:3306/notime?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: WeGame
    driver-class-name: com.mysql.jdbc.Driver
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka

  # 心跳检测检测与续约时间
  # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2
